name: 1.3 Deploy RDS

on:
  workflow_dispatch:

jobs:
  pulumi-rds:
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pulumi/actions@v4
        with:
          command: login
      - run: npm ci
      - name: Set bastionPublicKey secret
        run: pulumi config set service-infra:bastionPublicKey --secret "$BASTION_PUBLIC_KEY"
        env:
          BASTION_PUBLIC_KEY: ${{ secrets.BASTION_PUBLIC_KEY }}
      - name: Set rdsPassword secret
        run: pulumi config set service-infra:rdsPassword --secret "$RDS_PASSWORD"
        env:
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      - name: Pulumi up (RDS only)
        run: pulumi up --yes --target "urn:pulumi:dev::service-infra::custom:resource:RdsComponent::lg2m-service-rds"
